name: Sync Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/wiki/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Validate WIKI_TOKEN
        run: |
          if [ -z "${{ secrets.WIKI_TOKEN }}" ]; then
            echo "WIKI_TOKEN secret is not set" >&2
            exit 1
          fi

      - name: Sync docs/wiki -> Wiki
        uses: newrelic/wiki-sync-action@v1.0.1
        with:
          source: docs/wiki
          destination: wiki
          token: ${{ secrets.WIKI_TOKEN }}
          gitAuthorName: github-actions[bot]
          gitAuthorEmail: github-actions[bot]@users.noreply.github.com
